project 'FrameworkB.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrameworkB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FrameworkB
  pod 'FrameworkA', :path => '../FrameworkA.podspec'

  target 'FrameworkBTests' do
    # Pods for testing
  end

end
